version: '3'
services:
  notes_app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - notes_data:/data
    environment:
      - DATABASE_URL=/data/notes.db
      - PORT=8080
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env

volumes:
  notes_data:
